apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: kafdrop
    meta.helm.sh/release-namespace: kafka
  labels:
    app.kubernetes.io/instance: kafdrop
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafdrop
    helm.sh/chart: kafdrop-0.1.0
  name: kafdrop
  namespace: kafka
spec:
  clusterIP: 10.96.118.199
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30900
    port: 9000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: kafdrop
    app.kubernetes.io/name: kafdrop
  sessionAffinity: None
  type: NodePort
